(function(){if(typeof ncbi==="undefined")ncbi={};if(ncbi.sg)typeof console!=="undefined"&&console.error&&console.error("The logging JavaScript was added twice in the document. Please include it one time.");else{ncbi.sg=function(){};ncbi.sg.getInstance=function(){if(!ncbi.sg._instance)ncbi.sg._instance=new ncbi.sg;return ncbi.sg._instance};ncbi.sg._instance=null;ncbi.sg._version="21";(function(){var b=navigator.cookieEnabled?true:false;if(typeof navigator.cookieEnabled==="undefined"&&!b){document.cookie=
"testcookie";b=document.cookie.indexOf("testcookie")!==-1?true:false}ncbi.sg.isCookieEnabled=b})();ncbi.sg.appLogIgnore=["ncbi_sessionid","ncbi_clickdisabled"];ncbi.sg.prototype={init:function(){this.isProcessRunning=true;this._setUpMetaTagValues();if(this._cachedVals.ncbi_app&&this._cachedVals.ncbi_app.value.toLowerCase()=="entrez"&&this._cachedVals.ncbi_db&&this._cachedVals.ncbi_db.value.toLowerCase()=="gene"&&this._cachedVals.ncbi_report&&this._cachedVals.ncbi_report.value.toLowerCase()=="full_report")ncbi.sg.isScrollingEnabled=
true;this._setUpPathParts();this._setUpCustomProps();this._addOnScrollListeners();this.send("init");this._sendPrev();this._addPrintPing()},_vals:{},_cachedVals:{},_hasInitRun:false,_pathParts:{part1:"",part2:"",part3:"",part4:""},_setUpMetaTagValues:function(){for(var b=document.getElementsByTagName("meta"),a=0;a<b.length;a++){var d=b[a].name;d.indexOf("ncbi_")===0&&this.addEntry(d,b[a].content)}},_setUpCachedMetaTagValues:function(b){for(var a=0;a<b.length;a++){var d=this._cachedVals[b[a]];d&&this.addEntry(b[a],
d.value)}},cachedNames:["ncbi_app","ncbi_db","ncbi_pcid","ncbi_pdid","ncbi_phid","ncbi_sessionid","ncbi_uidlist"],ignoreLengthRestrictions:["jserror","jserrorlocation"],addEntry:function(b,a){if(!(a===undefined||a.length===0)){if(a.length>100&&this.ignoreLengthRestrictions.indexOf(b)===-1)a=a.substr(0,100);this._cachedVals[b]={sProp:b,value:a}}},removeAllEntries:function(){for(var b={},a=this.cachedNames.length,d=0;d<a;d++){var e=this.cachedNames[d],h=this._cachedVals[e];if(h)b[e]=h}this._cachedVals=
b;for(var m in this._pathParts)this._pathParts[m]=""},_setUpCustomProps:function(){var b=this._pathParts.part1,a=this._pathParts.part2.length>0?":"+this._pathParts.part2:"",d=this._pathParts.part3.length>0?":"+this._pathParts.part3:"",e=this._pathParts.part4.length>0?":"+this._pathParts.part4:"";b={pagename:b+a+d,server:window.location.hostname,sitesect2:b+a,subsect3:b+a+d,subsect4:b+a+d+e,heir1:(b+a+d+e).replace(/:/g,"|")};for(var h in b)this.addEntry(h,b[h]);this._sessionIdCheck();this._staticPageCheck();
this._prevHitCheck();this._browserConfigurationSettings();this._hashCheck()},_staticPageCheck:function(){this._cachedVals.ncbi_app&&this._cachedVals.ncbi_app.value.length>0||this.addEntry("ncbi_app","static");this._cachedVals.ncbi_pdid&&this._cachedVals.ncbi_pdid.value.length>0||this.addEntry("ncbi_pdid",(document.title||"unknown").replace(/\s+/g,""))},_sessionIdCheck:function(){if(!(this._cachedVals.ncbi_sessionid&&this._cachedVals.ncbi_sessionid.value.length>0)){var b="";if(b.length===0){var a=
this.getCookie("WebCubbyUser")||this.getCookie("WebEnv");if(a.length>0){a=unescape(a).split("@");if(a.length>1)b=a[a.length-1]}}if(b.length===0)b="NOSESSIONID";this.addEntry("ncbi_sessionid",b)}},getBrowserWidthHeight:function(){var b=this.getViewportWidth(),a=this.getViewportHeight();return{width:b,height:a}},_browserConfigurationSettings:function(){var b=this.getBrowserWidthHeight();this.addEntry("browserwidth",b.width);this.addEntry("browserheight",b.height);this.addEntry("screenwidth",screen.width);
this.addEntry("screenheight",screen.height);this.addEntry("screenavailwidth",screen.availWidth);this.addEntry("screenavailheight",screen.availHeight);if(document&&document.body){var a=document.body.scrollWidth,d=document.body.scrollHeight,e=d>b.height?"true":"false";this.addEntry("canscroll_x",a>b.width?"true":"false");this.addEntry("canscroll_y",e);this.addEntry("scrollheight",a);this.addEntry("scrollwidth",d)}if(screen.colorDepth)this.addEntry("colorDepth",screen.colorDepth);else screen.pixelDepth&&
this.addEntry("colorDepth",screen.pixelDepth)},_hashCheck:function(){var b=window.location.hash;if(b){b=b.replace("#","");this.addEntry("urlhash",b)}(b=window.location.search.match(/[?&]campaign=([^&]*)/))&&this.addEntry("campaign",b[1])},_createPHID:function(){var b=this._cachedVals.ncbi_sessionid.value,a=b.substr(0,15)+"9"+(new Date).getTime().toString(),d=b.length;a+=b.substr(d-(32-a.length),d);b={value:a};this.addEntry("ncbi_phid",a);return b},currentPageHitId:null,_prevHitCheck:function(){var b=
this.getCookie("ncbi_prevPHID"),a=this._cachedVals.ncbi_phid;b.length>0&&this.addEntry("prev_phid",b);if(!a||!a.value||a.value.length===0)a=this._createPHID();this.currentPageHitId=a.value;var d=this;ncbi.sg._hasFocus&&d.setCookie("ncbi_prevPHID",a.value);var e=window.onfocus;window.onfocus=function(h){d.getCookie("ncbi_prevPHID")!==a.value&&d.setCookie("ncbi_prevPHID",a.value);typeof e==="function"&&e(h)}},_setUpPathParts:function(){var b=this._cachedVals.ncbi_app,a=this._cachedVals.ncbi_db,d=this._cachedVals.ncbi_pdid,
e=this._cachedVals.ncbi_pcid;this._pathParts.part1=b!==undefined?b.value:"";this._pathParts.part2=a!==undefined?a.value:"";this._pathParts.part3=d!==undefined?d.value:"";this._pathParts.part4=e!==undefined?e.value:""},getPerfStats:function(){var b=window.performance;if(!b)return{};var a=b.timing;if(a)a={dns:a.domainLookupEnd-a.domainLookupStart,connect:a.connectEnd-a.connectStart,ttfb:a.responseStart-a.connectEnd,basePage:a.responseEnd-a.responseStart,frontEnd:a.loadEventStart-a.responseEnd};else return{};
if(b=b.navigation){a.navType=b.type;a.redirectCount=b.redirectCount}return a},setPerfStats:function(b,a){var d=this.getPerfStats();for(var e in d){var h=d[e];if(h>=0){var m="jsperf_"+e;if(a)b[m]=h;else b.push(m+"="+h)}}},send:function(b,a){var d=[];if(b==="init"){d.push("jsevent=render");ncbi.sg.renderTime=new Date;if(typeof ncbi_startTime!=="undefined"){d.push("jsrendertime="+(ncbi.sg.renderTime-ncbi_startTime));ncbi.sg.loadTime&&d.push("jsloadtime="+(ncbi.sg.loadTime-ncbi_startTime))}this.setPerfStats(d);
d.push("cookieenabled="+(ncbi.sg.isCookieEnabled?"true":"false"))}for(var e in this._cachedVals)ncbi.sg.appLogIgnore.indexOf(e)===-1&&d.push(e+"="+encodeURIComponent(this._cachedVals[e].value));this.sendAl(d.join("&"),a,true);this._hasInitRun=true;var h=this;setTimeout(function(){h.isProcessRunning=false;h.runSGProcess()},300)},_sendPrev:function(){var b=ncbi.sg.getInstance(),a=b.getCookie("clicknext");if(a){ncbi.sg.ping(a);b.setCookie("clicknext","")}if(a=b.getCookie("prevsearch")){ncbi.sg.ping(a);
b.setCookie("prevsearch","")}if(a=b.getCookie("unloadnext")){ncbi.sg.ping(a);b.setCookie("unloadnext","")}},sendAl:function(b,a,d){if(b.indexOf("jseventms")===-1)b+="&jseventms="+ncbi.sg.getInstance().getMillisecondsSinceSunday();b.match(/jsevent=search/i)&&this.setCookie("prevsearch",b.replace(/jsevent=search(next)?/i,"jsevent=searchnext"),null);b+="&sgVersion="+ncbi.sg._version;var e=window.location.port?":"+window.location.port:"";reqURL=typeof __ncbi_stat_url!=="undefined"?__ncbi_stat_url+"?"+
b:window.location.protocol+"//"+window.location.hostname+e+"/stat?"+b;this.makeAjaxCall(reqURL,function(){typeof a==="function"&&a()},d)},_processingQueue:[],isProcessRunning:false,addSGProcess:function(b){this._processingQueue.push(b)},getSGProcess:function(b){return this._processingQueue.shift(b)},runSGProcess:function(){if(this.isProcessRunning||this._processingQueue.length===0||!this._hasInitRun)return false;this.isProcessRunning=true;this.removeAllEntries();var b=this.getSGProcess();this._setUpCachedMetaTagValues(b.metadata);
this.addEntry("jsevent",b.eventName);for(var a in b.props)this.addEntry(a,b.props[a]);this.send(b.eventName,b.callbackFnc);var d=this;setTimeout(function(){d.isProcessRunning=false;d.runSGProcess()},300)},noteEventData:function(b,a,d,e){this.addSGProcess({eventName:b,props:a,metadata:d,callback:e});this.runSGProcess()},setCookie:function(b,a,d){if(window.sessionStorage)try{sessionStorage.setItem(b,a)}catch(e){}var h=new Date;d!==null&&h.setDate(h.getDate()+d);document.cookie=b+"="+escape(a)+(d===
null?"":"; expires="+h.toGMTString())+"; domain="+escape(".nih.gov")+"; path=/"},getCookie:function(b){var a;if(window.sessionStorage){try{a=sessionStorage.getItem(b)||""}catch(d){a=""}if(a.length>0)return a}if(document.cookie.length>0){a=document.cookie.indexOf(b+"=");if(a!==-1){a=a+b.length+1;b=document.cookie.indexOf(";",a);if(b===-1)b=document.cookie.length;return unescape(document.cookie.substring(a,b))}}return""},getTransport:function(){var b=null;if(window.XMLHttpRequest)try{b=new XMLHttpRequest;
this.getTransport=function(){return new XMLHttpRequest}}catch(a){b=null}if(window.ActiveXObject&&b===null)try{b=new ActiveXObject("Msxml2.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(d){try{b=new ActiveXObject("Microsoft.XMLHTTP");this.getTransport=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(e){b=false}}if(b===null)this.getTransport=function(){return null};return this.getTransport()},makeAjaxCall:function(b,a,d){var e=this.getTransport();
e.open("GET",b,d);if(d)e.onreadystatechange=function(){e.readyState===4&&a(e)};ncbi.sg.lastPing=e;e.send(null)},scrollDetails:{maxScroll_x:0,maxScroll_y:0,currScroll_x:0,currScroll_y:0,hasScrolled:false},scrollEventDetails:{xTenths:0,yTenths:0,xMax:0,yMax:0},_scrollEvents:[],_getScrollXY:function(){var b=this.getViewportHeight(),a=this.getViewportWidth(),d=document.body.scrollHeight,e=document.body.scrollHeight,h=Math.round((window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||
0)/b*10)/10;return{xRel:Math.round((window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0)/a*10)/10,yRel:h,viewportHeight:b,viewportWidth:a,pageHeight:d,pageWidth:e}},_addOnScrollListeners:function(){var b=window.onscroll,a=this;window.onscroll=function(){if(ncbi.sg.isScrollingEnabled)a._addScrollEvent();else{a._setScrollDetails();a.scrollDetails.hasScrolled=true}if(typeof b==="function")return b()}},getViewportHeight:function(){return window.innerHeight?window.innerHeight:
document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body!==null?document.body.clientHeight:"NA"},getViewportWidth:function(){return window.innerWidth?window.innerWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body!==null?document.body.clientWidth:"NA"},_setScrollDetails:function(){this.scrollDetails.currScroll_y=window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||
0;this.scrollDetails.currScroll_x=window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0;this.getViewportWidth();this.getViewportHeight();if(this.scrollDetails.maxScroll_y<this.scrollDetails.currScroll_y)this.scrollDetails.maxScroll_y=this.scrollDetails.currScroll_y;if(this.scrollDetails.maxScroll_x<this.scrollDetails.currScroll_x)this.scrollDetails.maxScroll_x=this.scrollDetails.currScroll_x},getScrollDetails:function(){if(!ncbi.sg.isScrollingEnabled){this._setScrollDetails();
var b=this.scrollDetails;l||(l={});for(var a in b)l[a]=b[a];return l}var d=this.scrollEventDetails;d.tstamp=(new Date).getTime();var e=this._getScrollXY(),h=e.xRel,m=e.yRel;l=null;if(!this._lastScroll||d.tstamp-this._lastScroll>1E3){this._scrollOrder=this._scrollOrder!=undefined?this._scrollOrder+1:0;b="yTenths."+this._scrollOrder+".scrollInfo";a="xTenths."+this._scrollOrder+".scrollInfo";var k="maxXTenths."+this._scrollOrder+".scrollInfo",s="maxYTenths."+this._scrollOrder+".scrollInfo",l={jsevent:"scroll"};
l["duration."+this._scrollOrder+".scrollInfo"]=this._lastScroll?d.tstamp-this._lastScroll:new Date-ncbi.sg.loadTime;l[a]=this.scrollEventDetails.xTenths;l[b]=this.scrollEventDetails.yTenths;l[k]=this.scrollEventDetails.xMax;l[s]=this.scrollEventDetails.yMax;if(b=this.scrollEventDetails.headings)for(a=0;a<b.length;a++){k=b[a];if(k.visible){if(k.id)l["id."+k.index+".headings."+this._scrollOrder+".scrollInfo"]=k.id;l["tagName."+k.index+".headings."+this._scrollOrder+".scrollInfo"]=k.tagName}}l["viewportHeight.scrollInfo"]=
e.viewportHeight;l["viewportWidth.scrollInfo"]=e.viewportWidth;l["maxPossibleScrollTenthsY."+this._scrollOrder+".scrollInfo"]=Math.round((e.pageHeight/e.viewportHeight-1)*10);l["maxPossibleScrollTenthsX."+this._scrollOrder+".scrollInfo"]=Math.round((e.pageWidth/e.viewportWidth-1)*10);l=l;this._scrollEvents=[]}this._lastScroll=d.tstamp;this.scrollEventDetails.xTenths=Math.round(h*10);this.scrollEventDetails.yTenths=Math.round(m*10);this.scrollEventDetails.xMax=Math.max(this.scrollEventDetails.xTenths,
this.scrollEventDetails.xMax);this.scrollEventDetails.yMax=Math.max(this.scrollEventDetails.yTenths,this.scrollEventDetails.yMax);b=[];d=document.getElementsByTagName("*");e=-1;for(a=0;a<d.length;a++){k=d[a];m=false;h=k.tagName.toLowerCase();for(s=0;s<7;s++)if(h=="h"+s)m=true;if(m){e+=1;k=k;m=k.offsetTop;s=k.offsetHeight;var C=window.pageYOffset,F=this.getViewportHeight(),u={};if(k=k.getAttribute("id")||k.id)u.id=k;u.index=e;u.tagName=h;u.visible=m+s>=C&&m<=C+F?true:false;b.push(u)}}this.scrollEventDetails.headings=
b;return l},addScrollDetails:function(b){var a=this.getScrollDetails();for(var d in a)b[d]=a[d]},_addScrollEvent:function(){try{var b=this.getScrollDetails();b&&ncbi.sg.ping(b)}catch(a){ncbi.sg.getInstance().noteEventData("jserror",{jserror:a.toString(),currenturl:window.location.href},["ncbi_sessionid","ncbi_phid"])}},_sliceScrollEvents:function(){for(var b=Math.ceil(this._scrollEvents.length/20),a=[],d=0;d<this._scrollEvents.length;d+=b)a.push(this._scrollEvents[d]);this._scrollEvents=a},_addPrintPing:function(){function b(){var e=
document.createElement("style");e.type="text/css";var h=document.createElement("style");h.type="text/css";h.media="print";for(var m=["jsevent=print"],k=0;k<a.cachedNames.length;k++){var s=a.cachedNames[k],l=a._cachedVals[s];l&&s!=="ncbi_sessionid"&&m.push(s+"="+encodeURIComponent(l.value))}m=".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }.print-log li { list-style-image: url('/stat?"+m.join("&")+"'); }";if(h.styleSheet){h.styleSheet.cssText=m;e.styleSheet.cssText=
".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"}else{h.appendChild(document.createTextNode(m));e.appendChild(document.createTextNode(".print-log { position:absolute;left:-10000px;top:auto;width:1px;height:1px;overflow:hidden; }"))}m=document.getElementsByTagName("head")[0];m.appendChild(h);m.appendChild(e);e=document.createElement("ul");e.className="print-log";h=document.createElement("li");e.appendChild(h);document.body.appendChild(e)}var a=this;if(typeof jQuery!==
"undefined")jQuery(b);else{var d=window.onload;window.onload=function(e){d&&d(e);b()}}},getMillisecondsSinceSunday:function(){var b=new Date,a=new Date;a.setDate(a.getDate()-a.getDay());a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return(b-a).toString(36)}};ncbi.sg.lastPing=null;ncbi.sg.hasNotedErrorEvent=false;(function(){function b(){ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);if(y.length>0)for(;y.length>0;)e(y.pop());var c={jsevent:"unload",
ncbi_pingaction:"unload"};if(typeof ncbi_startTime!=="undefined"){c.ncbi_timeonpage=new Date-ncbi_startTime;if(typeof ncbi_onloadTime!=="undefined"&&ncbi_onloadTime)c.ncbi_onloadTime=ncbi_onloadTime-ncbi_startTime}var f=ncbi.sg.getInstance();f.setPerfStats(c,true);f.addScrollDetails(c);if(!H){ncbi.sg.ping(c);var g="";for(var j in c)g+=j+"="+(j==="jsevent"?"unloadnext":c[j])+"&";g+="ncbi_phid="+f.currentPageHitId;f.setCookie("unloadnext",g,null)}H=true}function a(c){if(c){if(c.onclick)c.onclick_=c.onclick;
if(c.oncontextmenu)c.oncontextmenu_=c.oncontextmenu}}function d(c){for(var f=y.length-1;f>=-1;f--)if(y[f]===c){y.slice(f,1);break}e(c)}function e(c,f){if(I.indexOf(c.tstamp)===-1){I.push(c.tstamp);L.push(c);h("click",c,f)}}function h(c,f,g){var j=c==="click"?"link":"elem",i=f.link,r=f.evt,o=i.id||"",p=i.name||"",B=i.sid||"",z=i.href||"",v=i.innerText||i.textContent||"";if(v.length>50)v=v.substr(0,50);var w=i.getAttribute?i.getAttribute("ref")||i.ref||"":"",x=i.className?i.className.replace(/^\s?/,
"").replace(/\s?$/,"").split(/\s/g).join(",")||"":"";f=[];var A=[],t=i.parentNode;if(t)for(var q=0;q<6&&t!==null;q++){(parId=t.id)&&f.push(parId);if(parClassName=t.className)A=A.concat(parClassName.split(/\s/));t=t.parentNode}t=ncbi.sg.getInstance();q=t.currentPageHitId||"";var n=[];o.length>0&&n.push(j+"_id="+encodeURIComponent(o));p.length>0&&n.push(j+"_name="+encodeURIComponent(p));B.length>0&&n.push(j+"_sid="+encodeURIComponent(B));z.length>0&&n.push(j+"_href="+encodeURIComponent(z));v.length>
0&&n.push(j+"_text="+encodeURIComponent(v));x.length>0&&n.push(j+"_class="+encodeURIComponent(x));q=t.getBrowserWidthHeight();q.width!==null&&n.push("browserwidth="+encodeURIComponent(q.width));q.height!==null&&n.push("browserheight="+encodeURIComponent(q.height));for(var D in r){q=r[D];q!==undefined&&n.push(D.toLowerCase()+"="+q.toString())}n.push("jsevent="+c);w.length>0&&n.push(w);if(typeof jQuery!=="undefined")if(i=jQuery(i).attr("sg")){i=i.split(/\}\s*,\s*\{/);for(q=0;q<i.length;q++){r=i[q].match(/name\s*:\s*'(.+)',\s*selector\s*:\s*'(.+)'/);
if(r.length===3){D="cust_"+r[1];r=jQuery(r[2]).val();n.push(D+"="+encodeURIComponent(r))}}}if(g&&g.length>0)for(;g.length>0;)n.push(g.shift());f.length>0&&n.push("ancestorId="+f.join(","));A.length>0&&n.push("ancestorClassName="+A.join(",").replace(/\s+/g," ").replace(/(^\s|\s$)/g,""));if(c==="click"){c=n.join("&").replace("jsevent=click","jsevent=clicknext");q=ncbi.sg.getInstance().currentPageHitId||"";c+="&ncbi_phid="+q;t.setCookie("clicknext",c,null)}ncbi.sg.ping(n,true)}function m(c){var f={};
if(c){if(c.clientX||c.clientY){f.evt_coor_x=c.clientX+f.currScroll_x;f.evt_coor_y=c.clientY+f.currScroll_y}else if(c.pageX||c.pageY){f.evt_coor_x=c.pageX;f.evt_coor_y=c.pageY}f.jseventms=ncbi.sg.getInstance().getMillisecondsSinceSunday()}return f}function k(c,f,g){function j(o,p,B,z){function v(A){for(var t=[function(n){if(typeof n.preventDefault==="undefined")n.preventDefault=function(){this.returnValue=false};if(typeof n.stopPropagation==="undefined")n.stopPropagation=function(){this.cancelBubble=
true};return n}(o)],q=0;q<B.length;q++)t.push(B[q]);x=p[A].apply(p,t)}ncbi.sg.getInstance().setCookie("ncbi_prevPHID",ncbi.sg.getInstance().currentPageHitId);var w=m(o);w.iscontextmenu=z==="contextmenu"?"true":"false";w={evt:w,link:p,tstamp:(new Date).getTime(),floodTstamp:(new Date).getTime()};d(w);ncbi.sg.clickTimers&&window.clearTimeout(ncbi.sg.clickTimers);ncbi.sg.clickTimers=window.setTimeout(function(){ncbi.sg.clickTimers=null},300);var x=null;if(z==="click"&&typeof p.onclick_==="function")v("onclick_");
else z==="contextmenu"&&typeof p.oncontextmenu_==="function"&&v("oncontextmenu_");if(x!==null||x!==undefined)return x}for(var i=0;i<10&&f<g;i++){var r=c[f];if(r&&!r._sg){r._sg=true;a(r);r.onclick=function(o){var p=null;p=j(o||window.event,this,arguments,"click");if(p!==null||p!==undefined)return p};r.oncontextmenu=function(o){var p=null;p=j(o||window.event,this,arguments,"contextmenu");if(p!==null||p!==undefined)return p}}f++}f<g&&window.setTimeout(function(){k(c,f,g)},0)}function s(c){for(var f=
[],g=0;g<c.length;g++)f.push(c[g]);return f}function l(){if(ncbi.sg.isClickEnabled){var c=s(document.links);k(c,0,c.length);c=s(document.getElementsByTagName("button"));k(c,0,c.length);c=[];if(typeof jQuery!=="undefined")c=s(jQuery("input[type=button], input[type=submit], input[type=reset]").get());else{var f=s(document.getElementsByTagName("input"));c=[];for(var g=f.length-1;g>=0;){var j=f[g],i=j.type;if(i==="button"||i==="submit"||i==="reset")c.push(j);g--}}c.length>0&&k(c,0,c.length)}}function C(c,
f,g,j){var i={},r=null,o=null;if(typeof f==="string"){r=f;o=g}else{i=m(f);r=g;o=j}if(o){f=typeof o;if(f==="string")o=[o];else if(f==="object"&&!(o instanceof Array)){f=[];for(var p in o)f.push(p+"="+o[p]);o=f}}ncbi.sg.sendElementEvent(r,{link:c,evt:i},o)}function F(c,f){var g=[];if(typeof f==="undefined")f=true;if(typeof c==="object"&&!(c instanceof Array))for(var j in c)g.push(j+"="+encodeURIComponent(c[j]));else if(typeof c==="string")g.push(c);else g=c;c=ncbi.sg.getInstance().currentPageHitId||
"";j=null;if(typeof ncbi.sg.loadTime!=="undefined")j=new Date-ncbi.sg.loadTime;var i=g.join("&");if(i.indexOf("jsevent=clicknext")!==-1||i.indexOf("jsevent=searchnext")!==-1||i.indexOf("jsevent=unloadnext")!==-1){c.length>0&&g.push("next_phid="+encodeURIComponent(c));j!==null&&g.push("next_ncbi_timesinceload="+j)}else{c.length>0&&g.push("ncbi_phid="+encodeURIComponent(c));j!==null&&g.push("ncbi_timesinceload="+j)}ncbi.sg.getInstance().sendAl(g.join("&"),null,f)}var u=window.onerror;window.onerror=
function(c,f,g){if(!ncbi.sg.hasNotedErrorEvent){ncbi.sg.getInstance().noteEventData("jserror",{jserror:c,jserrorlocation:f,jserrorline:g,currenturl:window.location.href},["ncbi_sessionid","ncbi_phid"]);ncbi.sg.hasNotedErrorEvent=true;if(typeof u==="function")return u(c,f,g)}};var J=window.onbeforeunload;window.onbeforeunload=function(c){b();if(typeof J==="function")return J(c)};var y=[],I=[],L=[],H=false;ncbi.sg.sendElementEvent=h;ncbi.sg.clickTimers=[];if(typeof ncbi.sg.isClickEnabled==="undefined"){for(var G=
document.getElementsByTagName("meta"),E=G.length-1,K=true;E>=0;){if(G[E].name.toLowerCase()==="ncbi_clickdisabled"){K=G[E].content.toLowerCase()==="false";break}E--}ncbi.sg.isClickEnabled=K}l();ncbi.sg.scanLinks=function(c){if(c){if(typeof c==="object"&&!(c instanceof Array))c=[c];k(c,0,c.length)}else l()};ncbi.sg.ping=function(c,f,g,j){typeof c==="undefined"||c===null||(typeof c==="object"&&c.nodeName!==undefined?C(c,f,g,j):F(c,f))};ncbi.sg.loadTime=new Date})();if(!Array.prototype.indexOf)Array.prototype.indexOf=
function(b,a){var d=this.length>>>0;a=Number(a)||0;a=a<0?Math.ceil(a):Math.floor(a);if(a<0)a+=d;for(;a<d;a++)if(a in this&&this[a]===b)return a;return-1};(function(){function b(){ncbi_onloadTime=new Date}ncbi_onloadTime=null;if(typeof jQuery!=="undefined")jQuery(window).load(b);else{var a=window.onload;window.onload=function(d){a&&a(d);b()}}})()}})();

;
// This code creates window.console if it doesn't exist.
// It also creates stub functions for those functions that are missing in window.console.
// (Safari implements some but not all of the firebug window.console methods--this implements the rest.)
(function() {
    var names = [ "log", "debug", "info", "warn", "error", "assert", "dir", "dirxml", "group",
                  "groupEnd", "time", "timeEnd", "count", "trace", "profile", "profileEnd" ];

    if (typeof(console) === 'undefined' || typeof console === "function" ) {
      //"typeof function" is needed see PP-769 
      console = {};
    }

    for (var i = 0; i < names.length; ++i) {
       if (typeof(console[names[i]]) === 'undefined') {
          console[names[i]] = function() { return false; };
       }
    }
    ncbi.sg.getInstance().init();                          
})();
